### ISSUE TITLE
Error 404 when trying to post message

### ISSUE THREAD

**Issue by francos** [jenkinsci/yammer-plugin#10]
I'm trying to use this plugin to post a message to a group in Yammer, but I keep getting a 404 error, even though the group names I have tried with are valid.

Any idea what I could be doing wrong?

```
Sending Yammer notification...
ERROR: An error occurred while sending the Yammer notification.
the server responded with status 404
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response/raise_error.rb:6:in `on_complete'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:9:in `call'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:63:in `on_complete'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:107:in `get'
org/jruby/RubyBasicObject.java:1689:in `__send__'
org/jruby/RubyKernel.java:2111:in `send'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:33:in `request'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:22:in `get'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:38:in `get'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/throttle.rb:13:in `when_ready'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:36:in `get'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:17:in `get_autocomplete'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:22:in `groups_with_prefix'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:18:in `group_with_name'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:12:in `send'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/facade.rb:32:in `group_with_name'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:35:in `group_id'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:18:in `send_notification'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/models/yammer_notification_performer.rb:20:in `perform'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/models/yammer_notification.rb:19:in `perform'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/Users/Shared/Jenkins/Home/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'
```

**Comment by rdgreis** [comment]
Same here.

**Comment by daprog** [comment]
Installed this plugin today - same issue

**Comment by hirenpatel** [comment]
Same Issue here..

**Comment by mrbriandavis** [comment]
I made a fix for this plugin with this pull request. https://github.com/jenkinsci/yammer-plugin/pull/11
Can someone here take a look and see if this works for you?

**Comment by moszutij** [comment]
Thanks for the fix. The plugin works for me but I wasn't able to build or run it on a test server cleanly. I had to install the plugin's gem dependencies manually. Ideally, it should be possible to just run `rake build` or `rake serve`. 

When building the plugin, I noticed that the bundler only installs jenkins-plugin-runtime, json & slop but skips gems in the development group. I think this could be the cause of the problem.

When running the plugin on the test Jenkins sever, Jenkins reports `no such file to load -- hashie (LoadError)` when it tries to load `yammer_notification_performer.rb`. 

I'm not familiar with Ruby or the way bundling works, so not sure how it could be fixed. 

I have a clean Red Hat 6.x installation with JRuby and jpi installed

```
$ ruby -v
jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on OpenJDK 64-Bit Server VM 1.7.0_99-mockbuild_2016_03_24_16_39-b00 +jit [linux-amd64]
```

**Comment by mrbriandavis** [comment]
@moszutij - I will take a look at this and try fixing it.
