### ISSUE TITLE
Question regarding 401 Error

### ISSUE THREAD

**Issue by jsharifi** [jenkinsci/yammer-plugin#7]
Hello,

My company has been using the Yammer Plugin successfully for a few months now.  Sometime shortly after Dec 20 it stopped working for us.  The Yammer account works fine when sending a message manually to the particular group we use.  I even went through the process of creating a new Yammer app and getting a new access token, which made no difference.  Also, the Yammer account is an admin for the group.  Following is the error message from the Jenkins console output.  Thanks in advance for your help.  - Jon

Sending Yammer notification...
ERROR: An error occurred while sending the Yammer notification.
the server responded with status 401
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response/raise_error.rb:8:in `on_complete'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:9:in`call'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:63:in `on_complete'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:107:in`get'
org/jruby/RubyBasicObject.java:1689:in `__send__'
org/jruby/RubyKernel.java:2111:in`send'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:33:in `request'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:22:in`get'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:38:in `get'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/throttle.rb:13:in`when_ready'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:36:in `get'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:17:in`get_autocomplete'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:22:in `groups_with_prefix'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:18:in`group_with_name'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:12:in `send'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/facade.rb:32:in`group_with_name'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:35:in `group_id'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:18:in`send_notification'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_performer.rb:20:in `perform'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification.rb:19:in`perform'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in`boolean_result'
/var/lib/jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'

**Comment by flopo33** [comment]
Hi there,
same problem in here
- Access Token is available, and some GET calls in browser are working
- Ruby and Rails are installed on Jenkins Server
- User is Admin from Group

Only the Jenkins service is started with a different User as the yammer user, but i think this is not a problem.

@jsharifi: is your problem solved or do you have any other ideas?

**Comment by jsharifi** [comment]
Hi @flopo33, it appears Yammer has changed how apps authenticate, basically breaking existing apps.  What I've decided to do instead is use the Jenkins Email-Ext plugin to send an email in the format of "group+mycompany@yammer.com".  This will post messages just like the Yammer plugin.  The reason I'm using the Email-Ext plugin is because the default Jenkins email functionality only sends an email on failure.  Hope this helps.

**Comment by bvarner** [comment]
I just found this plugin and decided to give it a try. After going through the trouble of getting all the auth bits to work properly, I'm really really disappointed to see the 401 issue as well.

**Comment by flopo33** [comment]
Hi @jsharifi: that's a good idea and workaround.
the standard email functionality also sends on failure in my case.
so i tried Email-Ext but it also returns failure.

Error sending to the following INVALID addresses: Jenkins+company.de@yammer.com

Is it caused by the ".de" or what do you think? Any ideas?

**Comment by jsharifi** [comment]
@flopo33 we had a similar problem with our old smtp relay server because it didn't recognize an email address with a "+" in it as valid.
