### ISSUE TITLE
Error - status 410

### ISSUE THREAD

**Issue by glittle** [jenkinsci/yammer-plugin#8]
Here's what I get... any suggestions?

> Sending Yammer notification...
> ERROR: An error occurred while sending the Yammer notification.
> the server responded with status 410
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response/raise_error.rb:8:in `on_complete'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:9:in`call'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:63:in `on_complete'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in `run_request'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/faraday-0.8.7/lib/faraday/connection.rb:107:in`get'
> org/jruby/RubyBasicObject.java:1689:in `__send__'
> org/jruby/RubyKernel.java:2111:in`send'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:33:in `request'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yam-0.0.6/lib/yam/request.rb:22:in`get'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:38:in `get'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/throttle.rb:13:in`when_ready'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:36:in `get'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/client.rb:17:in`get_autocomplete'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:22:in `groups_with_prefix'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:18:in`group_with_name'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/requests/groups/group_with_name_request.rb:12:in `send'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/yamwow-0.1.6/lib/yamwow/facade.rb:32:in`group_with_name'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:35:in `group_id'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_sender.rb:18:in`send_notification'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification_performer.rb:20:in `perform'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/models/yammer_notification.rb:19:in`perform'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in`boolean_result'
> D:/CI/Jenkins/plugins/yammer/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'

**Comment by prasad0405** [comment]
Did you find the solution for this? If yes please post me back. Thank you.

**Comment by glittle** [comment]
No, I didn't get a solution.  I've given up trying to get Jenkins to notify me by any of the IM options.

**Comment by prasad0405** [comment]
Thank you.

Sent from Yahoo Mail on Android
